server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: security
    password: 3865

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 147521920274-9vtvlo25jcel8ua0etd6bib2kipgvo99.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: EaVXktplGUi9J_pJ0Tpt
            client-secret: WZoYctWcum
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: 9fcee9537206e292e3b5b5c734a2c0dd
            client-secret: 2MqjkqExcBIFgKKMVDIoxFWntwB5HXSX
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

          kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              user-name-attribute: id
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me




# kakao
# reset api key: 9fcee9537206e292e3b5b5c734a2c0dd
# secret key: 2MqjkqExcBIFgKKMVDIoxFWntwB5HXSX
# redirect url: http://localhost:8080/
# 응답받은 코드: https://kauth.kakao.com/oauth/authorize?client_id=9fcee9537206e292e3b5b5c734a2c0dd&redirect_uri=http://localhost:8080/&response_type=code
# 토큰 발급 요청 주소: https://kauth.kakao.com/oauth/token